blank_issues_enabled: true
contact_links:
  - name: General Support Request
    url: https://github.com/axewp/wp-graphql-gravity-forms/discussions
    about: For general help requests, create a new topic in Github Discussions
