name: Feature request
description: Suggest an idea for WPGraphQL for Gravity Forms
body:
  - type: markdown
    attributes:
      value: >-
        Thank you for taking the time to submit a feature request.


        Please make sure to search the repo for [existing feature
        requests](https://github.com/harness-software/wp-graphql-gravity-forms/issues?q=label%3A%22type%3A+enhancement+%E2%9A%A1%22+label%3A%22type%3A+feature+%F0%9F%A6%8B%22+label%3A%22type%3A+idea+%F0%9F%92%A1%22+)
        before creating a new one.
  - type: textarea
    attributes:
      label: What problem does this address?
      description: >-
        Please describe the problem you are trying to solve, including why you
        think this is a problem.
      placeholder: I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is your proposed solution?
      description: >-
        Please provide a clear and concise description of your suggested
        solution.
      placeholder: What I'd like to see happen is [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: What alternatives have you considered?
      description: >-
        Please list any alternatives you have considered, and why you think your
        solution is better.
  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
