<?php
/**
 * GraphQL Field - QuizFieldValue
 * Values for an individual Quiz field.
 *
 * @package WPGraphQL\GF\Type\WPObject\FormField\FieldProperties\ValueProperty
 * @since   0.9.1
 */

namespace WPGraphQL\GF\Type\WPObject\FormField\FieldValue;

use GF_Field;

/**
 * Class - QuizFieldValue
 */
class QuizFieldValue extends AbstractFieldValue {
	/**
	 * Type registered in WPGraphQL that we are adding the field to.
	 *
	 * @var string
	 */
	public static string $type = 'QuizField';

	/**
	 * Existing type registered in WPGraphQL that we are adding the field to.
	 *
	 * @var string
	 */
	public static string $field_name = 'values';

	/**
	 * {@inheritDoc}
	 */
	public static function get_description() : string {
		return __( 'Quiz field value.', 'wp-graphql-gravity-forms' );
	}

	/**
	 * {@inheritDoc}
	 */
	public static function get_field_type() : array {
		return [ 'list_of' => 'String' ];
	}

	/**
	 * Get the field value.
	 *
	 * @param array    $entry Gravity Forms entry.
	 * @param GF_Field $field Gravity Forms field.
	 */
	public static function get( array $entry, GF_Field $field ) : ?array {
		// Checkbox values are stored by each individual choice.
		switch ( $field->get_input_type() ) {
			case 'checkbox':
				$values = array_column( CheckboxFieldValue::get( $entry, $field ), 'value' ) ?? null;
				break;
			case 'radio':
				$values = RadioFieldValue::get( $entry, $field ) ?? null;
				break;
			case 'select':
				$values = SelectFieldValue::get( $entry, $field ) ?? null;
				break;
		}

		if ( empty( $values ) || ! class_exists( 'GFQuiz' ) ) {
			return null;
		}

		// Use the choice name, since the value is autogenerated gibberish.
		$actual_value = ( \GFQuiz::get_instance() )->maybe_format_field_values( $values, $field );

		/**
		 * String values are wrapped in an array to preserve a single output type.
		 *
		 * @todo convert once input unions are supported by GraphQL spec.
		 */
		return is_array( $actual_value ) ? $actual_value : [ $actual_value ];
	}
}
