name: Code Quality

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  run:
    runs-on: ubuntu-latest
    name: Check code
    services:
      mariadb:
        image: mariadb
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
        # Ensure docker waits for mariadb to start
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP w/ Composer & WP-CLI
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: mbstring, intl, bcmath, exif, gd, mysqli, opcache, zip, pdo_mysql
          coverage: none
          tools: composer, wp-cli

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php-${{ matrix.php }}-${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: php-${{ matrix.php }}N-${{ runner.os }}-composer

      - name: Install dependencies
        run: composer install --no-progress

      - name: Setup WordPress
        env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIT_USER: ${{ secrets.GIT_USER }}
        run: |
          cp .env.dist .env
          echo GIT_TOKEN=${{ secrets.GIT_TOKEN }} >> .env
          echo GIT_USER=${{ secrets.GIT_USER }} >> .env
          composer run install-stan-env
          cp -R . /tmp/wordpress/wp-content/plugins/wp-graphql-gravity-forms

      - name: Run PHPStan
        working-directory: /tmp/wordpress/wp-content/plugins/wp-graphql-gravity-forms
        run: composer run-script phpstan
